### ISSUE TITLE
Cannot find module in version 0.2.2

### ISSUE THREAD

**Issue by ssljivic** [jaredhanson/electrolyte#42]
I am getting the below error with version 0.2.2 when using following:

ioc.use('util', ioc.dir('app/util'));

This was working in version 0.2.0

The exception is:

```
Error: Cannot find module 'C:\code\test\app\util'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.app [as load] (C:\code\test\node_modules\electrolyte\lib\sources\dir.js:46:12)
    at Container._loadSpec (C:\code\test\node_modules\electrolyte\lib\container.js:194:18)
    at Container.create (C:\code\test\node_modules\electrolyte\lib\container.js:121:10)
    at FactorySpec.Spec.create (C:\code\test\node_modules\electrolyte\lib\spec.js:83:24)
    at Container.create (C:\code\test\node_modules\electrolyte\lib\container.js:131:18)
    at FactorySpec.Spec.create (C:\code\test\node_modules\electrolyte\lib\spec.js:83:24)
    at Container.create (C:\code\test\node_modules\electrolyte\lib\container.js:131:18)
    at FactorySpec.Spec.create (C:\code\test\node_modules\electrolyte\lib\spec.js:83:24)
    at Container.create (C:\code\test\node_modules\electrolyte\lib\container.js:131:18)
    at Object.<anonymous> (C:\code\test\app\main.js:9:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

**Comment by ssljivic** [comment]
To be precise, in version 0.2.0  this worked correctly:

```
ioc.use('util', ioc.node('app/util'));
```

But in version 0.2.2 I got a warning that node() is deprecated and that it should be replaced with dir(). When I did that, I got the above error.
